# Generated by Django 2.0 on 2019-06-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='user',
            field=models.CharField(default=1, max_length=10),
            preserve_default=False,
        ),
    ]
